USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_VENDEDORES_SELECIONAR]    Script Date: 07/08/2016 10:48:37 ******/
DROP PROCEDURE [dbo].[SPR_VENDEDORES_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPR_VENDEDORES_SELECIONAR]    Script Date: 07/08/2016 10:48:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROC [dbo].[SPR_VENDEDORES_SELECIONAR]
(
	@DOCUMENTO	VARCHAR(14) = NULL,
	@FL_ATIVO	BIT			= NULL
)
AS
BEGIN

	 SELECT V.ID_VENDEDOR AS ID_VENDEDOR_V,
			V.ID_ENDERECO AS ID_ENDERECO_VENDENDOR,
			V.ID_CONTATO AS ID_CONTATO_VENDEDOR,
			V.DOCUMENTO AS DOCUMENTO_VENDEDOR,
			V.COMISSAO AS COMISSAO_VENDEDOR,
			V.TP_VENDEDOR ,
			V.FL_ATIVO AS FL_ATIVO_VENDEDOR,
			V.NOME AS NOME_VENDEDOR,
			V.ID_SUPERIOR,
			
			E.ID_ENDERECO,
			E.RUA,
			E.NUMERO,
			E.COMPLEMENTO,
			E.CEP,
			E.BAIRRO,
			E.CIDADE,
			E.ESTADO,
	
			CO.ID_CONTATO,
			CO.NOME NOME_CONTATO,
			CO.EMAIL,
			CO.TELEFONE,
			CO.CELULAR			
	   FROM TB_VENDEDORES V
		    INNER JOIN TB_ENDERECO E ON
					   V.ID_ENDERECO = E.ID_ENDERECO
		    INNER JOIN TB_CONTATO CO ON
					   V.ID_CONTATO = CO.ID_CONTATO
	  WHERE V.DOCUMENTO = ISNULL(@DOCUMENTO, V.DOCUMENTO) AND
			V.FL_ATIVO = ISNULL (@FL_ATIVO, V.FL_ATIVO)
	  
END

GO


