USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_CONTATO_INSERIR]    Script Date: 07/08/2016 10:47:24 ******/
DROP PROCEDURE [dbo].[SPR_CONTATO_INSERIR]
GO

/****** Object:  StoredProcedure [dbo].[SPR_CONTATO_INSERIR]    Script Date: 07/08/2016 10:47:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROC [dbo].[SPR_CONTATO_INSERIR]
(
	@NOME			VARCHAR(100),
	@EMAIL			VARCHAR	(200),
	@TELEFONE		VARCHAR	(10),
	@CELULAR		VARCHAR	(11)
)
AS
BEGIN

	INSERT INTO TB_CONTATO
	(NOME, EMAIL, TELEFONE, CELULAR)
	VALUES
	(@NOME, @EMAIL, @TELEFONE, @CELULAR)
	
	SELECT @@IDENTITY	 

END

GO


