USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_CLIENTE_INSERIR]    Script Date: 07/08/2016 10:47:10 ******/
DROP PROCEDURE [dbo].[SPR_CLIENTE_INSERIR]
GO

/****** Object:  StoredProcedure [dbo].[SPR_CLIENTE_INSERIR]    Script Date: 07/08/2016 10:47:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROC [dbo].[SPR_CLIENTE_INSERIR]
(
	@NOME			VARCHAR	(500),
	@TP_PESSOA		VARCHAR	(2),
	@ID_ENDERECO	INT,
	@ID_CONTATO		INT,
	@FL_ATIVO		BIT,
	@DOCUMENTO		VARCHAR(14)
)
AS
BEGIN

	INSERT INTO TB_CLIENTE
	(NOME, TP_PESSOA, ID_ENDERECO, ID_CONTATO, FL_ATIVO, DOCUMENTO)
	VALUES
	(@NOME, @TP_PESSOA, @ID_ENDERECO, @ID_CONTATO, @FL_ATIVO, @DOCUMENTO)
	
	SELECT @@IDENTITY	 

END

GO


