USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_EQUIPAMENTOS_SELECIONAR]    Script Date: 07/08/2016 10:48:00 ******/
DROP PROCEDURE [dbo].[SPR_EQUIPAMENTOS_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPR_EQUIPAMENTOS_SELECIONAR]    Script Date: 07/08/2016 10:48:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROC [dbo].[SPR_EQUIPAMENTOS_SELECIONAR]
AS
BEGIN

	 SELECT ID_EQUIPAMENTO,
			MARCA,
			MODELO,
			NUMERO_SERIE
	   FROM TB_EQUIPAMENTOS

END

GO


