USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_CONTATO_ALTERAR]    Script Date: 07/08/2016 10:47:19 ******/
DROP PROCEDURE [dbo].[SPR_CONTATO_ALTERAR]
GO

/****** Object:  StoredProcedure [dbo].[SPR_CONTATO_ALTERAR]    Script Date: 07/08/2016 10:47:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROC [dbo].[SPR_CONTATO_ALTERAR]
(
	@ID_CONTATO		INT,
	@NOME			VARCHAR(100),
	@EMAIL			VARCHAR	(200),
	@TELEFONE		VARCHAR	(10),
	@CELULAR		VARCHAR	(11)
)
AS
BEGIN

	UPDATE TB_CONTATO
	   SET NOME = @NOME, 
		   EMAIL = @EMAIL, 
		   TELEFONE = @TELEFONE, 
		   CELULAR = @CELULAR
	 WHERE ID_CONTATO = @ID_CONTATO

END

GO


