USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_PAGAMENTO_ALTERAR]    Script Date: 07/08/2016 10:48:09 ******/
DROP PROCEDURE [dbo].[SPR_PAGAMENTO_ALTERAR]
GO

/****** Object:  StoredProcedure [dbo].[SPR_PAGAMENTO_ALTERAR]    Script Date: 07/08/2016 10:48:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROC [dbo].[SPR_PAGAMENTO_ALTERAR]
(
	@ID_PAGAMENTO	INT	= NULL,
	@FL_PAGO		BIT
)
AS
BEGIN

	UPDATE TB_PAGAMENTO
	   SET FL_PAGO = @FL_PAGO
	 WHERE ID_PAGAMENTO = @ID_PAGAMENTO

END
GO


