USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_PAGAMENTO_DELETAR]    Script Date: 07/08/2016 10:48:13 ******/
DROP PROCEDURE [dbo].[SPR_PAGAMENTO_DELETAR]
GO

/****** Object:  StoredProcedure [dbo].[SPR_PAGAMENTO_DELETAR]    Script Date: 07/08/2016 10:48:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROC [dbo].[SPR_PAGAMENTO_DELETAR]
(
	@ID_PAGAMENTO	INT
)
AS
BEGIN

	DELETE FROM TB_PAGAMENTO
	WHERE ID_PAGAMENTO = @ID_PAGAMENTO

END
GO


