USE [B2BSolution]
GO

/****** Object:  Table [dbo].[TB_CONTRATO]    Script Date: 07/08/2016 10:42:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TB_CONTRATO](
	[ID_CONTRATO] [int] IDENTITY(1,1) NOT NULL,
	[ID_CLIENTE] [int] NULL,
	[ID_EQUIPAMENTO] [int] NULL,
	[VL_CONSUMO_MINIMO] [decimal](18, 2) NULL,
	[DS_CADENCIA_FIXA] [varchar](6) NULL,
	[DS_CADENCIA_MOVEL] [varchar](6) NULL,
	[DT_CONTRATO] [datetime] NULL,
	[DIA_VENCIMENTO] [int] NULL,
	[VL_INSTALACAO] [decimal](18, 2) NULL,
	[ID_PRAZO_CONTRATUAL] [int] NULL,
	[ID_VENDEDOR] [int] NULL,
	[VL_TARIFA_LOCAL] [decimal](18, 2) NOT NULL DEFAULT ((0)),
	[VL_TARIFA_LDN] [decimal](18, 2) NOT NULL DEFAULT ((0)),
	[VL_TARIFA_VC1] [decimal](18, 2) NOT NULL DEFAULT ((0)),
	[VL_TARIFA_VC2] [decimal](18, 2) NOT NULL DEFAULT ((0)),
	[VL_TARIFA_VC3] [decimal](18, 2) NOT NULL DEFAULT ((0)),
	[VL_MENSALIDADE] [decimal](18, 2) NOT NULL DEFAULT ((0)),
PRIMARY KEY CLUSTERED 
(
	[ID_CONTRATO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TB_CONTRATO]  WITH CHECK ADD  CONSTRAINT [FK_CONTRATO_CLIENTE] FOREIGN KEY([ID_CLIENTE])
REFERENCES [dbo].[TB_CLIENTE] ([ID_CLIENTE])
GO

ALTER TABLE [dbo].[TB_CONTRATO] CHECK CONSTRAINT [FK_CONTRATO_CLIENTE]
GO

ALTER TABLE [dbo].[TB_CONTRATO]  WITH CHECK ADD  CONSTRAINT [FK_CONTRATO_EQUIPAMENTO] FOREIGN KEY([ID_EQUIPAMENTO])
REFERENCES [dbo].[TB_EQUIPAMENTOS] ([ID_EQUIPAMENTO])
GO

ALTER TABLE [dbo].[TB_CONTRATO] CHECK CONSTRAINT [FK_CONTRATO_EQUIPAMENTO]
GO

ALTER TABLE [dbo].[TB_CONTRATO]  WITH CHECK ADD  CONSTRAINT [FK_CONTRATO_VENDEDOR] FOREIGN KEY([ID_VENDEDOR])
REFERENCES [dbo].[TB_VENDEDORES] ([ID_VENDEDOR])
GO

ALTER TABLE [dbo].[TB_CONTRATO] CHECK CONSTRAINT [FK_CONTRATO_VENDEDOR]
GO


