USE [B2BSolution]
GO

/****** Object:  Table [dbo].[TB_EQUIPAMENTO_CONTRATO]    Script Date: 07/08/2016 10:43:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_EQUIPAMENTO_CONTRATO](
	[ID_EQUIPAMENTO_CONTRATO] [int] IDENTITY(1,1) NOT NULL,
	[ID_CONTRATO] [int] NULL,
	[ID_EQUIPAMENTO] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_EQUIPAMENTO_CONTRATO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[TB_EQUIPAMENTO_CONTRATO]  WITH CHECK ADD  CONSTRAINT [FK_V_CONTRATO_EQUIPAMENTO] FOREIGN KEY([ID_CONTRATO])
REFERENCES [dbo].[TB_CONTRATO] ([ID_CONTRATO])
GO

ALTER TABLE [dbo].[TB_EQUIPAMENTO_CONTRATO] CHECK CONSTRAINT [FK_V_CONTRATO_EQUIPAMENTO]
GO

ALTER TABLE [dbo].[TB_EQUIPAMENTO_CONTRATO]  WITH CHECK ADD  CONSTRAINT [FK_V_EQUIPAMENTO_CONTRATO] FOREIGN KEY([ID_EQUIPAMENTO])
REFERENCES [dbo].[TB_EQUIPAMENTOS] ([ID_EQUIPAMENTO])
GO

ALTER TABLE [dbo].[TB_EQUIPAMENTO_CONTRATO] CHECK CONSTRAINT [FK_V_EQUIPAMENTO_CONTRATO]
GO


