USE [B2BSolution]
GO

/****** Object:  Table [dbo].[TB_VENDEDORES]    Script Date: 07/08/2016 10:43:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TB_VENDEDORES](
	[ID_VENDEDOR] [int] IDENTITY(1,1) NOT NULL,
	[ID_ENDERECO] [int] NULL,
	[ID_CONTATO] [int] NULL,
	[DOCUMENTO] [varchar](14) NULL,
	[COMISSAO] [decimal](4, 2) NOT NULL,
	[TP_VENDEDOR] [int] NULL,
	[FL_ATIVO] [bit] NULL,
	[NOME] [varchar](500) NULL,
	[ID_SUPERIOR] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_VENDEDOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_DOCUMENTO_VENDEDORES] UNIQUE NONCLUSTERED 
(
	[DOCUMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TB_VENDEDORES]  WITH CHECK ADD  CONSTRAINT [FK_VENDEDORES_CONTATO] FOREIGN KEY([ID_CONTATO])
REFERENCES [dbo].[TB_CONTATO] ([ID_CONTATO])
GO

ALTER TABLE [dbo].[TB_VENDEDORES] CHECK CONSTRAINT [FK_VENDEDORES_CONTATO]
GO

ALTER TABLE [dbo].[TB_VENDEDORES]  WITH CHECK ADD  CONSTRAINT [FK_VENDEDORES_ENDERECO] FOREIGN KEY([ID_ENDERECO])
REFERENCES [dbo].[TB_ENDERECO] ([ID_ENDERECO])
GO

ALTER TABLE [dbo].[TB_VENDEDORES] CHECK CONSTRAINT [FK_VENDEDORES_ENDERECO]
GO

ALTER TABLE [dbo].[TB_VENDEDORES]  WITH CHECK ADD  CONSTRAINT [FK_VENDEDORES_TIPO] FOREIGN KEY([TP_VENDEDOR])
REFERENCES [dbo].[TB_TIPO_VENDEDORES] ([ID_TIPO_VENDEDOR])
GO

ALTER TABLE [dbo].[TB_VENDEDORES] CHECK CONSTRAINT [FK_VENDEDORES_TIPO]
GO


